version: '3'

services:
  app:
    build:
      context: .
      args:
        # Argumentos de build para o estágio de build
        NODE_ENV: production
        VITE_API_URL: /api
        # Adicione outros argumentos de build conforme necessário
    ports:
      - "8080:80"
    environment:
      # Variáveis de ambiente para o contêiner em execução
      - NODE_ENV=production
      - API_URL=/api
      # Adicione outras variáveis de ambiente conforme necessário
      # - REACT_APP_SUPABASE_URL=https://seu-projeto.supabase.co
      # - REACT_APP_SUPABASE_ANON_KEY=sua-chave-anonima
    restart: unless-stopped
    # Descomente as linhas abaixo para montar volumes para desenvolvimento
    # volumes:
    #   - ./dist:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
