
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnpvzhalxogrmgdckdmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ucHZ6aGFseG9ncm1nZGNrZG12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNzIyMDIsImV4cCI6MjA1NTY0ODIwMn0.eQyjlx6w8bEgJsey92HSDmTZrrIaShzsMLSANsmTzns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Re-export adapters, utils, and mock data
export * from './adapters';
export * from './mockData';
export * from './utils';
