
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import './database.types'; // Import our extended types

const SUPABASE_URL = "https://msgjsjauuhzdxwajbphj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zZ2pzamF1dWh6ZHh3YWpicGhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMjI3MTMsImV4cCI6MjA1Nzc5ODcxM30.A7yiKoGkYA6iul1JqsXqR9O9HhS6Q14wrtoDLG_kmnw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
