
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { mockUserData as mockUsers, mockClients as mockClientData, mockPermissions as mockPermissionData, 
  mockPermissionGroups as mockPermissionGroupData, mockActivityLogs as mockActivityLogData } from './mockData';
import { userAdapter, clientAdapter, permissionAdapter, permissionGroupAdapter, activityLogsAdapter, departmentAdapter } from './adapters';

const SUPABASE_URL = "https://ddivdksbsgcxdgzrlpoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkaXZka3Nic2djeGRnenJscG95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1NjU0OTksImV4cCI6MjA1MzE0MTQ5OX0.DpS2OgWDK7dBDx-M5PZtq5cuPiVE0OsGkfW_LpzH8JA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Export mock data for development
export const mockUserData = mockUsers;
export const mockClients = mockClientData;
export const mockPermissions = mockPermissionData;
export const mockPermissionGroups = mockPermissionGroupData;
export const mockActivityLogs = mockActivityLogData;

// Export adapters
export { userAdapter, clientAdapter, permissionAdapter, permissionGroupAdapter, activityLogsAdapter, departmentAdapter };
